export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  GET_ALL_USER_REQUEST: "GET_ALL_USER_REQUEST",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_USER_FAILURE: "GET_ALL_USER_FAILURE",
  GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",
  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
  SEARCH_USER_REQUEST: "SEARCH_USER_REQUEST",
  SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
  SEARCH_USER_FAILURE: "SEARCH_USER_FAILURE",
};

export const meetingConstants = {
  GET_ALL_MEETING_REQUEST: "GET_ALL_MEETING_REQUEST",
  GET_ALL_MEETING_SUCCESS: "GET_ALL_MEETING_SUCCESS",
  GET_ALL_MEETING_FAILURE: "GET_ALL_MEETING_FAILURE",
  GET_MEETING_DETAILS_REQUEST: "GET_MEETING_DETAILS_REQUEST",
  GET_MEETING_DETAILS_SUCCESS: "GET_MEETING_DETAILS_SUCCESS",
  GET_MEETING_DETAILS_FAILURE: "GET_MEETING_DETAILS_FAILURE",
  UPDATE_MEETING_REQUEST: "UPDATE_MEETING_REQUEST",
  UPDATE_MEETING_SUCCESS: "UPDATE_MEETING_SUCCESS",
  UPDATE_MEETING_FAILURE: "UPDATE_MEETING_FAILURE",
  CREATE_MEETING_REQUEST: "CREATE_MEETING_REQUEST",
  CREATE_MEETING_SUCCESS: "CREATE_MEETING_SUCCESS",
  CREATE_MEETING_FAILURE: "CREATE_MEETING_FAILURE",
  DELETE_MEETING_REQUEST: "DELETE_MEETING_REQUEST",
  DELETE_MEETING_SUCCESS: "DELETE_MEETING_SUCCESS",
  DELETE_MEETING_FAILURE: "DELETE_MEETING_FAILURE",
  SEARCH_MEETING_REQUEST: "SEARCH_MEETING_REQUEST",
  SEARCH_MEETING_SUCCESS: "SEARCH_MEETING_SUCCESS",
  SEARCH_MEETING_FAILURE: "SEARCH_MEETING_FAILURE",
};

export const featureConstants = {
  GET_ALL_FEATURE_REQUEST: "GET_ALL_FEATURE_REQUEST",
  GET_ALL_FEATURE_SUCCESS: "GET_ALL_FEATURE_SUCCESS",
  GET_ALL_FEATURE_FAILURE: "GET_ALL_FEATURE_FAILURE",
  GET_FEATURE_DETAILS_REQUEST: "GET_FEATURE_DETAILS_REQUEST",
  GET_FEATURE_DETAILS_SUCCESS: "GET_FEATURE_DETAILS_SUCCESS",
  GET_FEATURE_DETAILS_FAILURE: "GET_FEATURE_DETAILS_FAILURE",
  UPDATE_FEATURE_REQUEST: "UPDATE_FEATURE_REQUEST",
  UPDATE_FEATURE_SUCCESS: "UPDATE_FEATURE_SUCCESS",
  UPDATE_FEATURE_FAILURE: "UPDATE_FEATURE_FAILURE",
  DELETE_FEATURE_REQUEST: "DELETE_FEATURE_REQUEST",
  DELETE_FEATURE_SUCCESS: "DELETE_FEATURE_SUCCESS",
  DELETE_FEATURE_FAILURE: "DELETE_FEATURE_FAILURE",
  SEARCH_FEATURE_REQUEST: "SEARCH_FEATURE_REQUEST",
  SEARCH_FEATURE_SUCCESS: "SEARCH_FEATURE_SUCCESS",
  SEARCH_FEATURE_FAILURE: "SEARCH_MEETING_FAILURE",
};
export const roleConstants = {
  GET_ALL_ROLE_REQUEST: "GET_ALL_ROLE_REQUEST",
  GET_ALL_ROLE_SUCCESS: "GET_ALL_ROLE_SUCCESS",
  GET_ALL_ROLE_FAILURE: "GET_ALL_ROLE_FAILURE",
};
export const All_PERMISSIONS = [
  "WRITE_MEETING",
  "WRITE_FEATURE",
  "HOST_MEETING",
  "MANAGE_MEETING",
  "WRITE_USER",
  "WRITE_ROLE",
  "READ_USER",
];

export const permissionConstants = {
  WRITE_MEETING: "WRITE_MEETING",
  WRITE_FEATURE: "WRITE_FEATURE",
  HOST_MEETING: "HOST_MEETING",
  MANAGE_MEETING: "MANAGE_MEETING",
  WRITE_USER: "WRITE_USER",
  WRITE_ROLE: "WRITE_ROLE",
  READ_USER: "READ_USER",
};
